services:
  - type: web
    name: giasuhq-backend
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: JPA_DDL_AUTO
        value: update
      - key: SQL_INIT_MODE
        value: never
      - key: CORS_ORIGINS
        value: https://tutors-fe.vercel.app
      - key: VNPAY_TMN_CODE
        value: 6NQ5V6GO
      - key: VNPAY_HASH_SECRET
        value: UBSXLCRDVNJYZBIFXYMTQTCFHRYJAAOS
      - key: VNPAY_PAY_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNPAY_RETURN_URL
        value: https://tutors-fe.vercel.app/#payment-result
